# Mixin of Effective Dart, Google Pedantic and Flutter style linter rules for the SzikApp project.
# Comment out the unnecessary rules below linter/rules, do not change priority levels.

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Error rules
    avoid_empty_else: error
    avoid_relative_lib_imports: error
    avoid_types_as_parameter_names: error
    avoid_web_libraries_in_flutter: error
    cancel_subscriptions: error
    close_sinks: error
    control_flow_in_finally: error
    empty_statements: error
    hash_and_equals: warning
    no_duplicate_case_values: error
    prefer_relative_imports: warning
    test_types_in_equals: error
    throw_in_finally: error
    unnecessary_statements: error
    unrelated_type_equality_checks: error
    valid_regexps: error

    # Style rules
    always_declare_return_types: error
    always_require_non_null_named_parameters: warning
    annotate_overrides: error
    avoid_catches_without_on_clauses: warning
    avoid_catching_errors: error
    avoid_classes_with_only_static_members: error
    # avoid_dynamic_calls: warning
    avoid_equals_and_hash_code_on_mutable_classes: warning
    avoid_function_literals_in_foreach_calls: warning
    avoid_init_to_null: error
    avoid_null_checks_in_equality_operators: error
    avoid_positional_boolean_parameters: warning
    avoid_private_typedef_functions: error
    avoid_return_types_on_setters: warning
    avoid_returning_null: error
    avoid_returning_this: error
    avoid_setters_without_getters: warning
    avoid_shadowing_type_parameters: error
    avoid_types_on_closure_parameters: warning
    avoid_void_async: info
    await_only_futures: warning
    camel_case_extensions: info
    constant_identifier_names: info
    curly_braces_in_flow_control_structures: warning
    directives_ordering: info
    empty_catches: warning
    empty_constructor_bodies: warning
    file_names: info
    implementation_imports: warning
    library_names: info
    library_prefixes: info
    lines_longer_than_80_chars: info
    non_constant_identifier_names: info
    null_closures: warning
    omit_local_variable_types: warning
    one_member_abstracts: warning
    only_throw_errors: warning
    package_api_docs: info
    package_prefixed_library_names: info
    parameter_assignments: warning
    prefer_adjacent_string_concatenation: warning
    prefer_collection_literals: warning
    prefer_conditional_assignment: warning
    prefer_contains: warning
    prefer_equal_for_default_values: warning
    prefer_final_fields: warning
    prefer_for_elements_to_map_fromIterable: warning
    prefer_function_declarations_over_variables: warning
    prefer_generic_function_type_aliases: warning
    prefer_if_null_operators: warning
    prefer_initializing_formals: warning
    prefer_interpolation_to_compose_strings: warning
    prefer_is_empty: warning
    prefer_is_not_empty: warning
    prefer_iterable_whereType: warning
    prefer_mixin: warning
    prefer_single_quotes: info
    prefer_spread_collections: warning
    public_member_api_docs: info
    recursive_getters: warning
    slash_for_doc_comments: info
    sized_box_for_whitespace: info
    type_annotate_public_apis: warning
    type_init_formals: warning
    unawaited_futures: warning
    unnecessary_brace_in_string_interps: warning
    unnecessary_const: warning
    unnecessary_getters_setters: warning
    unnecessary_lambdas: warning
    unnecessary_new: warning
    unnecessary_null_in_if_null_operators: warning
    unnecessary_this: warning
    use_function_type_syntax_for_parameters: warning
    use_rethrow_when_possible: warning
    use_setters_to_change_properties: warning
    use_to_and_as_if_applicable: warning

    # Pub rules
    package_names: info

linter:
  rules:
    # Error rules
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_types_as_parameter_names: true
    #- avoid_web_libraries_in_flutter
    cancel_subscriptions: true
    #- close_sinks
    #- control_flow_in_finally
    #- empty_statements
    hash_and_equals: true
    #- no_duplicate_case_values
    prefer_relative_imports: true
    #- test_types_in_equals
    #- throw_in_finally
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    valid_regexps: true

    ## Style rules
    always_declare_return_types: true
    #- always_require_non_null_named_parameters
    #- annotate_overrides
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    #- avoid_classes_with_only_static_members
    #- avoid_dynamic_calls: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    #- avoid_function_literals_in_foreach_calls
    #- avoid_init_to_null
    #- avoid_null_checks_in_equality_operators
    avoid_positional_boolean_parameters: true
    avoid_private_typedef_functions: true
    #- avoid_return_types_on_setters
    avoid_returning_null: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_shadowing_type_parameters: true
    #- avoid_types_on_closure_parameters
    avoid_void_async: true
    await_only_futures: true
    camel_case_extensions: true
    #- constant_identifier_names
    directives_ordering: true
    empty_catches: true
    empty_constructor_bodies: true
    #- file_names
    #- implementation_imports
    library_names: true
    library_prefixes: true
    #- lines_longer_than_80_chars
    non_constant_identifier_names: true
    #- null_closures
    omit_local_variable_types: true
    #- one_member_abstracts
    only_throw_errors: true
    #- package_api_docs
    #- package_prefixed_library_names
    parameter_assignments: true
    #- prefer_adjacent_string_concatenation
    #- prefer_collection_literals
    #- prefer_conditional_assignment
    #- prefer_contains
    #- prefer_equal_for_default_values
    #- prefer_final_fields
    #- prefer_for_elements_to_map_fromIterable
    #- prefer_function_declarations_over_variables
    #- prefer_generic_function_type_aliases
    #- prefer_if_null_operators
    #- prefer_initializing_formals
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    #- prefer_iterable_whereType
    #- prefer_mixin
    prefer_single_quotes: true
    #- prefer_spread_collections
    # - public_member_api_docs
    #- recursive_getters
    slash_for_doc_comments: true
    sized_box_for_whitespace: true
    type_annotate_public_apis: true
    #- type_init_formals
    #- unawaited_futures
    #- unnecessary_brace_in_string_interps
    #- unnecessary_const
    #- unnecessary_getters_setters
    unnecessary_lambdas: true
    #- unnecessary_new
    #- unnecessary_null_in_if_null_operators
    #- unnecessary_this
    #- use_function_type_syntax_for_parameters
    #- use_rethrow_when_possible
    #use_setters_to_change_properties: true
    use_to_and_as_if_applicable: true
#
    ## Pub rules
    #- package_names
    