# Mixin of Effective Dart, Google Pedantic and Flutter style linter rules for the SzikApp project.
# Comment out the unnecessary rules below linter/rules, do not change priority levels.

# The flutter_lints package is a superset of the dart:lints package. FLutter yaml includes rules
# from the lints/recommended.yaml and that contains lints/core.yaml.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Error rules
    cancel_subscriptions: error
    close_sinks: error
    prefer_relative_imports: warning
    prefer_void_to_null: error
    test_types_in_equals: error
    throw_in_finally: error
    unnecessary_statements: error

    # Style rules
    always_declare_return_types: error
    annotate_overrides: error
    avoid_catches_without_on_clauses: warning
    avoid_catching_errors: error
    avoid_classes_with_only_static_members: error
    avoid_dynamic_calls: warning
    avoid_equals_and_hash_code_on_mutable_classes: warning
    avoid_positional_boolean_parameters: warning
    avoid_private_typedef_functions: error
    avoid_returning_this: error
    avoid_setters_without_getters: warning
    avoid_types_on_closure_parameters: warning
    avoid_void_async: info
    directives_ordering: info
    eol_at_end_of_file: info
    lines_longer_than_80_chars: info
    omit_local_variable_types: warning
    one_member_abstracts: warning
    only_throw_errors: warning
    package_api_docs: info
    parameter_assignments: warning
    prefer_mixin: warning
    prefer_single_quotes: info
    public_member_api_docs: info
    type_annotate_public_apis: warning
    unawaited_futures: warning
    unnecessary_lambdas: warning
    use_setters_to_change_properties: warning
    use_to_and_as_if_applicable: warning

linter:
  rules:
    # Error rules
    cancel_subscriptions: true
    #- close_sinks
    prefer_relative_imports: true
    prefer_void_to_null: true
    #- test_types_in_equals
    throw_in_finally: true
    unnecessary_statements: true

    ## Style rules
    always_declare_return_types: true
    annotate_overrides: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    #- avoid_classes_with_only_static_members
    #- avoid_dynamic_calls
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_positional_boolean_parameters: true
    avoid_private_typedef_functions: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_shadowing_type_parameters: true
    #- avoid_types_on_closure_parameters
    avoid_void_async: true
    directives_ordering: true
    eol_at_end_of_file: true
    #- lines_longer_than_80_chars
    omit_local_variable_types: true
    one_member_abstracts: true
    only_throw_errors: true
    #- package_api_docs
    parameter_assignments: true
    #- prefer_mixin
    prefer_single_quotes: true
    # - public_member_api_docs
    type_annotate_public_apis: true
    #- unawaited_futures
    unnecessary_lambdas: true
    #use_setters_to_change_properties: true
    use_to_and_as_if_applicable: true
    