name: szikapp
description: Awesome application for doing business in da SZIK.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+33

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cupertino_icons: ^1.0.3
  json_annotation: ^4.1.0
  easy_localization: ^3.0.0
  shared_preferences: ^2.0.7
  # Firebase:
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.1
  firebase_crashlytics: ^2.2.1
  firebase_analytics: ^8.3.2
  firebase_performance: ^0.7.1
  firebase_dynamic_links: ^2.0.10
  google_sign_in: ^5.1.0
  url_launcher: ^6.0.10
  flutter_signin_button: ^2.0.0
  provider: ^6.0.0
  delayed_display: ^2.0.0
  persistent_bottom_nav_bar: ^4.0.2
  shimmer: ^2.0.0
  dropdown_search: ^0.6.1
  uuid: ^3.0.4
  accordion: ^1.0.4
  connectivity_plus: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  json_serializable: ^5.0.0
  flutter_native_splash: ^1.2.3
  flutter_lints: ^1.0.4

flutter_native_splash:
  # After change, run this command:
  # flutter clean && flutter pub get
  # flutter pub run flutter_native_splash:create
  color: "#59A3B0"
  image: assets/pictures/logo_white_800.png
  android: true
  ios: true
  # Dark mode
  color_dark: "#444444"
  image_dark: "assets/pictures/logo_white_800.png"
  

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/pictures/
    - assets/pictures/boardgames/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Nunito/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Nunito/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Nunito/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Nunito/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
