name: szikapp
description: Awesome application for doing business in da SZIK.
authors:
  - Csertán Tamás <csertan.tamas@szentignac.hu>
  - Sárvári Márk <sarvari.mark@szentignac.hu>

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  cupertino_icons: ^1.0.2
  json_annotation: ^4.0.1
  easy_localization:
  shared_preferences: ^2.0.5
  # Firebase:
  firebase_core: ^1.0.3
  firebase_auth: ^1.1.0
  google_sign_in: ^5.0.2
  url_launcher: ^6.0.3
  flutter_signin_button: ^2.0.0
  provider: ^5.0.0
  delayed_display: ^2.0.0
  google_fonts: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.1
  json_serializable: ^4.1.0
  pedantic: ^1.9.2
  flutter_native_splash: ^1.1.7+1

flutter_native_splash:
  # After change, run this command:
  # flutter clean && flutter pub get
  # flutter pub run flutter_native_splash:create
  color: "#59A3B0"
  image: assets/pictures/logo_white_800.png
  android: true
  ios: true
  # Dark mode
  color_dark: "#444444"
  image_dark: "assets/pictures/logo_white_800.png"
  

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/pictures/