import 'package:json_annotation/json_annotation.dart';

enum GroupPermission {
  @JsonValue('createAllTask')
  createAllTask,
  @JsonValue('readAllTask')
  readAllTask,
  @JsonValue('editAllTask')
  editAllTask,
  @JsonValue('createAgendaTask')
  createAgendaTask,
  @JsonValue('readAgendaTask')
  readAgendaTask,
  @JsonValue('editAgendaTask')
  editAgendaTask,
  @JsonValue('createTimetableTask')
  createTimetableTask,
  @JsonValue('readTimetableTask')
  readTimetableTask,
  @JsonValue('editTimetableTask')
  editTimetableTask,
  @JsonValue('createJanitorTask')
  createJanitorTask,
  @JsonValue('readJanitorTask')
  readJanitorTask,
  @JsonValue('editJanitorTask')
  editJanitorTask,
  @JsonValue('createReservationTask')
  createReservationTask,
  @JsonValue('readReservationTask')
  readReservationTask,
  @JsonValue('editReservationTask')
  editReservationTask,
  @JsonValue('createCleaningTask')
  createCleaningTask,
  @JsonValue('readCleaningTask')
  readCleaningTask,
  @JsonValue('editCleaningTask')
  editCleaningTask,
  @JsonValue('createBookloanTask')
  createBookloanTask,
  @JsonValue('readBookloanTask')
  readBookloanTask,
  @JsonValue('editBookloanTask')
  editBookloanTask,

  @JsonValue('createGroups')
  createGroups,
  @JsonValue('readGroups')
  readGroups,
  @JsonValue('editGroups')
  editGroups,
  @JsonValue('createUsers')
  createUsers,
  @JsonValue('readUsers')
  readUsers,
  @JsonValue('editUsers')
  editUsers
}
