import 'package:json_annotation/json_annotation.dart';

enum GroupPermission {
  @JsonValue('createAllTask')
  CAN_CREATE_ALL_TASK,
  @JsonValue('readAllTask')
  CAN_READ_ALL_TASK,
  @JsonValue('editAllTask')
  CAN_EDIT_ALL_TASK,
  @JsonValue('createAgendaTask')
  CAN_CREATE_AGENDA_TASK,
  @JsonValue('readAgendaTask')
  CAN_READ_AGENDA_TASK,
  @JsonValue('editAgendaTask')
  CAN_EDIT_AGENDA_TASK,
  @JsonValue('createTimetableTask')
  CAN_CREATE_TIMETABLE_TASK,
  @JsonValue('readTimetableTask')
  CAN_READ_TIMETABLE_TASK,
  @JsonValue('editTimetableTask')
  CAN_EDIT_TIMETABLE_TASK,
  @JsonValue('createJanitorTask')
  CAN_CREATE_JANITOR_TASK,
  @JsonValue('readJanitorTask')
  CAN_READ_JANITOR_TASK,
  @JsonValue('editJanitorTask')
  CAN_EDIT_JANITOR_TASK,
  @JsonValue('createReservationTask')
  CAN_CREATE_RESERVATION_TASK,
  @JsonValue('readReservationTask')
  CAN_READ_RESERVATION_TASK,
  @JsonValue('editReservationTask')
  CAN_EDIT_RESERVATION_TASK,
  @JsonValue('createCleaningTask')
  CAN_CREATE_CLEANING_TASK,
  @JsonValue('readCleaningTask')
  CAN_READ_CLEANING_TASK,
  @JsonValue('editCleaningTask')
  CAN_EDIT_CLEANING_TASK,
  @JsonValue('createBookloanTask')
  CAN_CREATE_BOOKLOAN_TASK,
  @JsonValue('readBookloanTask')
  CAN_READ_BOOKLOAN_TASK,
  @JsonValue('editBookloanTask')
  CAN_EDIT_BOOKLOAN_TASK,

  @JsonValue('createGroups')
  CAN_CREATE_GROUPS,
  @JsonValue('readGroups')
  CAN_READ_GROUPS,
  @JsonValue('editGroups')
  CAN_EDIT_GROUPS,
  @JsonValue('createUsers')
  CAN_CREATE_USERS,
  @JsonValue('readUsers')
  CAN_READ_USERS,
  @JsonValue('editUsers')
  CAN_EDIT_USERS
}
