name: SzikAPP - build & deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-android:
    name: Android releaser
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.2'
    - run: flutter pub get
    - run: flutter build appbundle
    - uses: actions/upload-artifact@v2
      with:
        name: SzikAPP - test
        path: build/app/outputs/bundle/release/app-release.aab
  
  #build-ios:
  #  name: IOS releaser
  #  runs-on: macos-latest
  #  steps:
  #  - uses: actions/checkout@v2
  #  - uses: actions/setup-java@v1
  #    with:
  #      java-version: '12.x'
  #  - uses: subosito/flutter-action@v1
  #    with:
  #      flutter-version: '1.22.6'
  #  - run: flutter pub get
  #  - run: flutter build ios --no-codesign
  #  - uses: actions/upload-artifact@v2
  #    with:
  #      name: SzikAPP - test
  #      path: build/ios/
  
